
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.List;
import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListSelectionEvent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luke
 */
public class CCGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CCGUI() {
        initComponents();
       
    }
     DefaultListModel listModel = new DefaultListModel();
     DefaultListModel carListModel = new DefaultListModel();
     DefaultListModel empRouteListModel = new DefaultListModel();
     DefaultListModel carRouteListModel = new DefaultListModel();
     DefaultListModel fareListModel = new DefaultListModel();
     JButton empButton = new JButton("Add");
     JButton carButton = new JButton("Add");
     ArrayList<Fare> fareRunList = new ArrayList<Fare>();
     ArrayList<Employee> empRunList = new ArrayList<Employee>();
     ArrayList<Cars> carRunList = new ArrayList<Cars>();

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        empList = empList = new javax.swing.JList(listModel);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dlNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dlState = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cumlMiles = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        empNotes = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        saveEmp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hDate = new javax.swing.JTextField();
        fDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        infractions = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cumPay = new javax.swing.JTextField();
        yearPay = new javax.swing.JTextField();
        empProfit = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        hurrrrrrrrrr = new javax.swing.JLabel();
        hurrr = new javax.swing.JLabel();
        plateNum = new javax.swing.JTextField();
        carModel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        carColour = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        carYear = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        carNum = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        carCumMiles = new javax.swing.JTextField();
        addCar = new javax.swing.JButton();
        removeCar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        carNotes = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        carSaveChanges = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        carAdded = new javax.swing.JTextField();
        carRemoved = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        carMaint = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        carList = carList = new javax.swing.JList(carListModel);
        jLabel11 = new javax.swing.JLabel();
        carInsp = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        carCumMaint = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        carProfit = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        empRouteList = empRouteList = new javax.swing.JList(listModel);
        jScrollPane6 = new javax.swing.JScrollPane();
        carRouteList = carRouteList = new javax.swing.JList(carListModel);
        updateButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        expMiles = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        expTime = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        fareDriver = new javax.swing.JTextField();
        carFare = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        fareList = fareList = new javax.swing.JList(fareListModel);
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        postExpectedMiles = new javax.swing.JTextField();
        postExpectedTime = new javax.swing.JTextField();
        postDriver = new javax.swing.JTextField();
        postCar = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        actualMiles = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        actualTime = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        fareFee = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        empFarePay = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        gasCost = new javax.swing.JTextField();
        postProfit = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();

        fileChooser.setDialogTitle("Choose a session to open\n");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(51, 153, 255));

        jTabbedPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setToolTipText("");

        empList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        empList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                empListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(empList);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("DL Number");

        jLabel4.setText("DL State");

        jLabel5.setText("Employee #");

        empNum.setToolTipText("");

        jLabel6.setText("Cumulative Miles Driven");

        jButton1.setText("Add Employee");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jButton2.setText("Remove Employee");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased1(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        empNotes.setColumns(20);
        empNotes.setRows(5);
        jScrollPane1.setViewportView(empNotes);

        jLabel8.setText("Employee Notes");

        saveEmp.setText("Save Changes");
        saveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmpActionPerformed(evt);
            }
        });

        jLabel7.setText("Hire Date");

        jLabel9.setText("Fire Date");

        jLabel10.setText("Infractions");

        jLabel22.setText("Cumulative Pay");

        jLabel23.setText("Employee Profit");

        jLabel24.setText("Year to date Pay");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(saveEmp)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel22))
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fName, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(lName)
                                        .addComponent(dlNum)
                                        .addComponent(dlState, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cumPay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel24)
                                .addComponent(jLabel23))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(infractions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(fDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cumlMiles)
                                .addComponent(yearPay)
                                .addComponent(empProfit))
                            .addGap(100, 100, 100))
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel8))
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cumlMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(hDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(dlNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(fDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(dlState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(infractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(yearPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(cumPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(empProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(saveEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane3.addTab("Employees", jPanel1);

        jPanel2.setToolTipText("");

        hurrrrrrrrrr.setText("License Plate");

        hurrr.setText("Model");

        jLabel13.setText("Colour");

        jLabel14.setText("Year");

        jLabel15.setText("Car Number");

        carNum.setToolTipText("");

        jLabel16.setText("Cumulative Miles Driven");

        addCar.setText("Add Car");
        addCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addCarMouseReleased1(evt);
            }
        });

        removeCar.setText("Remove Car");
        removeCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                removeCarMouseReleased1(evt);
                removeCarMouseReleased(evt);
            }
        });
        removeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarActionPerformed(evt);
            }
        });

        carNotes.setColumns(20);
        carNotes.setRows(5);
        jScrollPane4.setViewportView(carNotes);

        jLabel17.setText("Car Notes");

        carSaveChanges.setText("Save Changes");
        carSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carSaveChangesActionPerformed(evt);
            }
        });

        jLabel18.setText("Added");

        jLabel19.setText("Removed");

        jLabel20.setText("Last Maintenance");

        carList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        carList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                carListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(carList);

        jLabel11.setText("Last Inspection");

        jLabel25.setText("Cumulative Maintence Cost");

        jLabel26.setText("Car Profit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(addCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeCar, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hurrr, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hurrrrrrrrrr, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel25))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(plateNum, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(carModel)
                                    .addComponent(carColour)
                                    .addComponent(carYear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(carCumMaint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel11)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(carMaint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(carRemoved, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(carAdded, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(carCumMiles)
                                .addComponent(carInsp)
                                .addComponent(carProfit))
                            .addGap(100, 100, 100)))
                    .addComponent(jLabel17)
                    .addComponent(carSaveChanges))
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hurrrrrrrrrr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plateNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(carCumMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hurrr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(carAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(carColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(carRemoved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(carYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(carMaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(carNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(carInsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(carCumMaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(carProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(carSaveChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeCar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Fleet 1", jPanel2);

        jTabbedPane3.addTab("Cars", jTabbedPane1);

        empRouteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        empRouteList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                empRouteListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(empRouteList);

        carRouteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        carRouteList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                carRouteListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(carRouteList);

        updateButton.setText("Update Fare");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Expected Miles");

        jLabel21.setText("Expected Time");

        expTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expTimeActionPerformed(evt);
            }
        });

        jLabel27.setText("Driver");

        jLabel28.setText("Car");

        jButton3.setText("Create Fare");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });

        fareList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fareList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fareListValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(fareList);

        jLabel29.setText("Drivers");

        jLabel30.setText("Cars");

        jLabel31.setText("Fares");

        jLabel32.setText("Expected Miles");

        jLabel33.setText("Expected Time");

        jLabel34.setText("Driver");

        jLabel35.setText("Car");

        postCar.setText(" ");

        jLabel36.setText("Actual Miles");

        jLabel37.setText("Actual Time");

        jLabel38.setText("Fare Fee");

        jLabel39.setText("Employee Pay");

        jLabel40.setText("Gas Cost");

        jLabel41.setText("Profit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fareDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(expMiles, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(expTime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carFare, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empFarePay, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(fareFee))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateButton)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(postExpectedMiles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(postExpectedTime)
                                    .addComponent(postDriver)
                                    .addComponent(postCar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(actualMiles)
                                    .addComponent(actualTime)
                                    .addComponent(gasCost)
                                    .addComponent(postProfit)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel31)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(postExpectedMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(postExpectedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(postDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(postCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(actualMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actualTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gasCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(postProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel12))
                            .addComponent(expMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(fareDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carFare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(fareFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empFarePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(0, 102, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Monday", jPanel3);

        jTabbedPane3.addTab("Plan Route", jTabbedPane2);

        jMenu1.setText("File");

        Open.setText("Open Session");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Save.setText("Save Session");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Save);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        Edit.setText("Edit");
        jMenuBar1.add(Edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

        final JFrame nameFrame = new JFrame();
        nameFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nameFrame.setSize(500, 500);
        nameFrame.setDefaultLookAndFeelDecorated(true);
        //JButton empButton = new JButton("Add");
        final JTextField empNameField = new JTextField();
        //nameFrame.add(empNameField);
        nameFrame.add(empNameField, BorderLayout.CENTER);
        nameFrame.add(empButton, BorderLayout.LINE_END);
        nameFrame.setDefaultLookAndFeelDecorated(true);
        empButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Employee tempEmp = new Employee(empNameField.getText());
                tempEmp.listName= empNameField.getText();
                tempEmp.empNum=1;
                empRunList.add(tempEmp);
 
                
                empRouteListModel.addElement(tempEmp);
                
                listModel.addElement(tempEmp);

                empList.validate();
                empRouteList.validate();
                empNameField.setText(null);
                nameFrame.dispose();
            }
        });
        //empButton.addActionListener(this);

        nameFrame.pack();
        nameFrame.setVisible(true);
       
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased1
        empList.remove(empList.getSelectedIndex());
        empList.validate();
    }//GEN-LAST:event_jButton2MouseReleased1

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
    int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
//        try {
//          // What to do with the file, e.g. display it in a TextArea
//          textarea.read( new FileReader( file.getAbsolutePath() ), null );
//        } catch (IOException ex) {
//          System.out.println("problem accessing file"+file.getAbsolutePath());
//        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_OpenActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
         System.exit(0);  
    }//GEN-LAST:event_ExitActionPerformed

    private void saveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmpActionPerformed
    //int selectedIndex = empList.getSelectedIndex();
     Employee tempEmp = (Employee) empList.getSelectedValue();
     for (int x = 0; x < empRunList.size(); x++){
        
        if (empRunList.get(x).getEmpID() == tempEmp.getEmpID()){
            empRunList.get(x).firstName = fName.getText();
            empRunList.get(x).lastName = lName.getText();
            empRunList.get(x).listName = tempEmp.listName;
            empRunList.get(x).dl = Integer.parseInt(dlNum.getText());
            empRunList.get(x).dlState = dlState.getText();
            empRunList.get(x).empNum = Integer.parseInt(empNum.getText());
            empRunList.get(x).cumlMiles = Integer.parseInt(cumlMiles.getText());
            empRunList.get(x).empNotes= empNotes.getText();
            empRunList.get(x).hireDate = hDate.getText();
            empRunList.get(x).fireDate = fDate.getText();
            empRunList.get(x).inf = infractions.getText();
            empRunList.get(x).cumPay = Integer.parseInt(cumPay.getText());
            empRunList.get(x).yearPay = Integer.parseInt(yearPay.getText());
            empRunList.get(x).empProfit = Integer.parseInt(empProfit.getText());
            

        }

    }
        
    }//GEN-LAST:event_saveEmpActionPerformed

    private void empListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_empListValueChanged
        Employee tempEmp = (Employee) empList.getSelectedValue();
        fName.setText(tempEmp.getFirstName());
        lName.setText(tempEmp.getLastName());
        dlState.setText(tempEmp.getdlState());
        empNum.setText(Integer.toString(tempEmp.getEmpID()));
        dlNum.setText(Integer.toString(tempEmp.getdl()));
        cumlMiles.setText(Integer.toString(tempEmp.getCumMiles()));
        empNotes.setText(tempEmp.getempNotes());
        hDate.setText(tempEmp.gethdate());
        fDate.setText(tempEmp.getfdate());
        infractions.setText(tempEmp.getInf());
        cumPay.setText(Integer.toString(tempEmp.getCumPay()));
        yearPay.setText(Integer.toString(tempEmp.getYearPay()));
        empProfit.setText(Integer.toString(tempEmp.getEmpProfit()));

    }//GEN-LAST:event_empListValueChanged

    private void removeCarMouseReleased1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCarMouseReleased1
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCarMouseReleased1

    private void removeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCarActionPerformed

    private void carSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carSaveChangesActionPerformed
     Cars tempEmp = (Cars) carList.getSelectedValue();
     for (int x = 0; x < carRunList.size(); x++){

        if (carRunList.get(x).getCarNum() == tempEmp.getCarNum()){
         
            carRunList.get(x).carColour = carColour.getText();
            carRunList.get(x).carNotes = carNotes.getText();
            carRunList.get(x).carAdded = carAdded.getText();
            carRunList.get(x).carCumMiles = Integer.parseInt(carCumMiles.getText());
            carRunList.get(x).carListName = tempEmp.carListName;
            carRunList.get(x).carModel = carModel.getText();
            carRunList.get(x).carNum = Integer.parseInt(carNum.getText());
            carRunList.get(x).carRemoved= carRemoved.getText();
            carRunList.get(x).carYear = carYear.getText();
            carRunList.get(x).lastIns = carInsp.getText();
            carRunList.get(x).lastMaint = carMaint.getText();
            carRunList.get(x).plateNum = plateNum.getText();
            carRunList.get(x).carCumMaint = Integer.parseInt(carCumMaint.getText());
            carRunList.get(x).carProfit = Integer.parseInt(carProfit.getText());

        }

    }

        
    }//GEN-LAST:event_carSaveChangesActionPerformed

    private void addCarMouseReleased1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCarMouseReleased1
        final JFrame nameFrame = new JFrame();
        nameFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nameFrame.setSize(500, 500);
        nameFrame.setDefaultLookAndFeelDecorated(true);
        //JButton empButton = new JButton("Add");
        final JTextField carNameField = new JTextField();
        //nameFrame.add(empNameField);
        nameFrame.add(carNameField, BorderLayout.CENTER);
        nameFrame.add(carButton, BorderLayout.LINE_END);
        nameFrame.setDefaultLookAndFeelDecorated(true);
        carButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Cars tempCar = new Cars(carNameField.getText());
                tempCar.carListName= carNameField.getText();
                tempCar.carNum=1;
                carRunList.add(tempCar);
                
                carRouteListModel.addElement(tempCar);
                carListModel.addElement(tempCar);

                carList.validate();
                carRouteList.validate();
                carNameField.setText(null);
                nameFrame.dispose();
            }
        });
        //empButton.addActionListener(this);

        nameFrame.pack();
        nameFrame.setVisible(true);
       
    }//GEN-LAST:event_addCarMouseReleased1

    private void carListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_carListValueChanged
                                    
        Cars tempEmp = (Cars) carList.getSelectedValue();
        plateNum.setText(tempEmp.getPlateNum());
        carModel.setText(tempEmp.getCarModel());
        carColour.setText(tempEmp.getCarColour());
        carYear.setText(tempEmp.getCarYear());
        carNum.setText(Integer.toString(tempEmp.getCarNum()));
        carCumMiles.setText(Integer.toString(tempEmp.getCarCumMiles()));
        carAdded.setText(tempEmp.getCarAdded());
        carRemoved.setText(tempEmp.getCarRemoved());
        carMaint.setText(tempEmp.getLastMaint());
        carInsp.setText(tempEmp.getLastIns());
        carNotes.setText(tempEmp.getCarNotes());
        carCumMaint.setText(Integer.toString(tempEmp.getCarCumMaint()));
        carProfit.setText(Integer.toString(tempEmp.getCarProfit()));

                        
    }//GEN-LAST:event_carListValueChanged

    private void removeCarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCarMouseReleased

    private void expTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expTimeActionPerformed

    private void empRouteListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_empRouteListValueChanged
    Employee tempEmp = (Employee) empList.getSelectedValue();
    fareDriver.setText(tempEmp.getListName());

    }//GEN-LAST:event_empRouteListValueChanged

    private void carRouteListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_carRouteListValueChanged
        Cars tempCar = (Cars) carList.getSelectedValue();
        carFare.setText(tempCar.getCarListName());
    }//GEN-LAST:event_carRouteListValueChanged

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        Employee tempEmp = (Employee) empRouteList.getSelectedValue();
        Cars tempCar = (Cars) carRouteList.getSelectedValue();
//        Fare tempFare = new Fare();
        Fare tempFare = new Fare(tempEmp, tempCar, expMiles.getText(), expTime.getText(), Integer.parseInt(fareFee.getText()), Integer.parseInt(empFarePay.getText()));
        fareListModel.addElement(tempFare);

    }//GEN-LAST:event_jButton3MouseReleased

    private void fareListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fareListValueChanged
        Fare tempFare = (Fare) fareList.getSelectedValue();
        postExpectedMiles.setText(tempFare.getExpectMiles());
        postExpectedTime.setText(tempFare.getExpectedTime());
        postDriver.setText(tempFare.getFareListName());
        postCar.setText(tempFare.getCarListName());
    }//GEN-LAST:event_fareListValueChanged

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    try(BufferedReader br = new BufferedReader(new FileReader("GPSData.txt"))) {
        StringBuilder sb = new StringBuilder();
        String line = br.readLine();

        while (line != null) {
            sb.append(line);
            
            sb.append(System.lineSeparator());
            line = br.readLine(); 
//            actualMiles.setText(br.readLine());
//            actualTime.setText(br.readLine());
        }
        String everything = sb.toString();
        actualMiles.setText(everything);
        actualTime.setText(everything);
    }   catch (FileNotFoundException ex) {       
            Logger.getLogger(CCGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CCGUI.class.getName()).log(Level.SEVERE, null, ex);
        }   
    
    //calculating profits
    postProfit.setText(Integer.toString(Integer.parseInt(fareFee.getText())-Integer.parseInt(gasCost.getText())-Integer.parseInt(empFarePay.getText())));
    
    Employee tempEmp = (Employee) empRouteList.getSelectedValue();
    tempEmp.cumPay = tempEmp.cumPay+Integer.parseInt(empFarePay.getText());
    cumPay.setText(Integer.toString(tempEmp.cumPay));
    tempEmp.yearPay = tempEmp.yearPay+Integer.parseInt(empFarePay.getText());
    yearPay.setText(Integer.toString(tempEmp.yearPay));
    tempEmp.empProfit = tempEmp.empProfit+(Integer.parseInt(fareFee.getText())-Integer.parseInt(empFarePay.getText())-Integer.parseInt(gasCost.getText()));
    empProfit.setText(Integer.toString(tempEmp.empProfit));
    
    Cars tempCar = (Cars) carRouteList.getSelectedValue();
    tempCar.carProfit= tempCar.carProfit+(Integer.parseInt(fareFee.getText())-Integer.parseInt(gasCost.getText()));
    carProfit.setText(Integer.toString(tempCar.carProfit));
//    tempCar.carCumMiles = tempCar.carCumMiles+(Integer.parseInt(actualMiles.getText()));
//    carCumMiles.setText(Integer.toString(tempCar.carCumMiles));
    int alertMiles = 0;
    int alertTime =0;
    alertMiles = Integer.parseInt(actualMiles.getText())-Integer.parseInt(expMiles.getText());
    alertTime = Integer.parseInt(actualTime.getText())-Integer.parseInt(expTime.getText());
    if ( alertMiles > 40 ){
        
    }
    
    if (alertTime > 40){
        
    }
    
    }//GEN-LAST:event_updateButtonActionPerformed
    
    
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try {
            OutputStream file = new FileOutputStream("empRunList.ser");
            OutputStream buffer = new BufferedOutputStream(file);
            ObjectOutput output = new ObjectOutputStream(buffer);
            output.writeObject(empRunList);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CCGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CCGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               CCGUI x = new CCGUI();
  
               x.pack();
               x.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JTextField actualMiles;
    private javax.swing.JTextField actualTime;
    private javax.swing.JButton addCar;
    private javax.swing.JTextField carAdded;
    private javax.swing.JTextField carColour;
    private javax.swing.JTextField carCumMaint;
    private javax.swing.JTextField carCumMiles;
    private javax.swing.JTextField carFare;
    private javax.swing.JTextField carInsp;
    private javax.swing.JList carList;
    private javax.swing.JTextField carMaint;
    private javax.swing.JTextField carModel;
    private javax.swing.JTextArea carNotes;
    private javax.swing.JTextField carNum;
    private javax.swing.JTextField carProfit;
    private javax.swing.JTextField carRemoved;
    private javax.swing.JList carRouteList;
    private javax.swing.JButton carSaveChanges;
    private javax.swing.JTextField carYear;
    private javax.swing.JTextField cumPay;
    private javax.swing.JTextField cumlMiles;
    private javax.swing.JTextField dlNum;
    private javax.swing.JTextField dlState;
    private javax.swing.JTextField empFarePay;
    private javax.swing.JList empList;
    private javax.swing.JTextArea empNotes;
    private javax.swing.JTextField empNum;
    private javax.swing.JTextField empProfit;
    private javax.swing.JList empRouteList;
    private javax.swing.JTextField expMiles;
    private javax.swing.JTextField expTime;
    private javax.swing.JTextField fDate;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fareDriver;
    private javax.swing.JTextField fareFee;
    private javax.swing.JList fareList;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField gasCost;
    private javax.swing.JTextField hDate;
    private javax.swing.JLabel hurrr;
    private javax.swing.JLabel hurrrrrrrrrr;
    private javax.swing.JTextField infractions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField plateNum;
    private javax.swing.JTextField postCar;
    private javax.swing.JTextField postDriver;
    private javax.swing.JTextField postExpectedMiles;
    private javax.swing.JTextField postExpectedTime;
    private javax.swing.JTextField postProfit;
    private javax.swing.JButton removeCar;
    private javax.swing.JButton saveEmp;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField yearPay;
    // End of variables declaration//GEN-END:variables
}
